import type { ScamAlertItem} from "../types/scamAlerts";

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

const mock = [
    {
        id: 1,
        title: 'Спорная комиссия за чарджбэки',
        description: 'Партнёр удерживает повышенную комиссию по возвратам',
        type: 'chargeback',
        severity: 'critical',
        status: 'open',
        isCommunityConfirmed: true,
        node: { name: 'BitStore', shortName: 'MR' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 9,
        createdAt: '2026-07-05',
        riskTrendDays: 14,
    },
    {
        id: 2,
        title: 'Подозрение в участии в AML-схемах',
        description: 'Есть подозрительные транзакции',
        type: 'fraud',
        severity: 'critical',
        status: 'open',
        isCommunityConfirmed: false,
        node: { name: 'BitStore', shortName: 'MR' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 9,
        createdAt: '2026-07-05',
        riskTrendDays: 9,
    },
    {
        id: 3,
        title: 'Длительная задержка выплат без объяснений',
        description: 'Выплаты не приходят более 10 дней',
        type: 'delay',
        severity: 'high',
        status: 'watching',
        isCommunityConfirmed: true,
        node: { name: 'BitStore', shortName: 'MR' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 9,
        createdAt: '2026-07-05',
        riskTrendDays: 12,
    },
    {
        id: 4,
        title: 'Не выплачивает уже 3 месяца',
        description: 'Есть массовые жалобы на невыплаты',
        type: 'scam',
        severity: 'critical',
        status: 'open',
        isCommunityConfirmed: false,
        node: { name: 'CashFlow', shortName: 'CF' },
        reporter: { name: 'Delta', shortName: 'DL' },
        confirmationsCount: 8,
        createdAt: '2026-07-05',
        riskTrendDays: 20,
    },
    {
        id: 5,
        title: 'Аномально высокий уровень чарджбэков (>3%)',
        description: 'Фиксируется аномальный рост возвратов',
        type: 'chargeback',
        severity: 'medium',
        status: 'watching',
        isCommunityConfirmed: false,
        node: { name: 'FastPay', shortName: 'FP' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 9,
        createdAt: '2026-07-05',
        riskTrendDays: 6,
    },
    {
        id: 6,
        title: 'Возможная схема с фродовыми картами',
        description: 'Есть серия однотипных подозрительных платежей',
        type: 'fraud',
        severity: 'low',
        status: 'watching',
        isCommunityConfirmed: false,
        node: { name: 'Nova', shortName: 'NV' },
        reporter: { name: 'Delta', shortName: 'DL' },
        confirmationsCount: 9,
        createdAt: '2026-07-05',
        riskTrendDays: 3,
    },
    {
        id: 7,
        title: 'Повторная спорная комиссия за чарджбэки',
        description: 'Партнёр повторно увеличил комиссию без предупреждения',
        type: 'chargeback',
        severity: 'critical',
        status: 'open',
        isCommunityConfirmed: true,
        node: { name: 'BitStore', shortName: 'MR' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 10,
        createdAt: '2026-07-06',
        riskTrendDays: 7,
    },
    {
        id: 8,
        title: 'Серия спорных AML-флагов',
        description: 'Появились массовые кейсы необоснованной блокировки',
        type: 'fraud',
        severity: 'high',
        status: 'watching',
        isCommunityConfirmed: false,
        node: { name: 'FastPay', shortName: 'FP' },
        reporter: { name: 'Sigma', shortName: 'SG' },
        confirmationsCount: 4,
        createdAt: '2026-07-06',
        riskTrendDays: 5,
    },
    {
        id: 9,
        title: 'Нестабильная обработка возвратов',
        description: 'Часть операций зависает на ручной проверке',
        type: 'chargeback',
        severity: 'medium',
        status: 'watching',
        isCommunityConfirmed: true,
        node: { name: 'Nova', shortName: 'NV' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 5,
        createdAt: '2026-07-06',
        riskTrendDays: 4,
    },
    {
        id: 10,
        title: 'Подозрение на скам-сценарий',
        description: 'Есть сообщения о резком ухудшении условий работы',
        type: 'scam',
        severity: 'critical',
        status: 'open',
        isCommunityConfirmed: false,
        node: { name: 'CashFlow', shortName: 'CF' },
        reporter: { name: 'Sigma', shortName: 'SG' },
        confirmationsCount: 12,
        createdAt: '2026-07-06',
        riskTrendDays: 18,
    },
    {
        id: 11,
        title: 'Серая воронка платежей',
        description: 'Подозрение на обход стандартного маршрута обработки',
        type: 'fraud',
        severity: 'high',
        status: 'watching',
        isCommunityConfirmed: false,
        node: { name: 'Orbit', shortName: 'OR' },
        reporter: { name: 'Delta', shortName: 'DL' },
        confirmationsCount: 3,
        createdAt: '2026-07-07',
        riskTrendDays: 8,
    },
    {
        id: 12,
        title: 'Скачок возвратов по BIN-группе',
        description: 'Отмечен локальный всплеск чарджбэков',
        type: 'chargeback',
        severity: 'medium',
        status: 'watching',
        isCommunityConfirmed: false,
        node: { name: 'Orbit', shortName: 'OR' },
        reporter: { name: 'Twix', shortName: 'TW' },
        confirmationsCount: 6,
        createdAt: '2026-07-07',
        riskTrendDays: 2,
    },
] satisfies ScamAlertItem[]

export const getScamAlerts = async (): Promise<ScamAlertItem[]> => {
    await wait(3000)
    return mock
}